<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Load students data from JSON file
        $jsonPath = database_path('seeders/students.json');
        $studentsData = json_decode(file_get_contents($jsonPath), true);

        foreach ($studentsData as $student) {
            // The student_id will be auto-generated by the model
            Student::create($student);
        }
    }
}
